# Generated by Django 5.0.6 on 2024-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rssfeed_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DefaultSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds', models.ManyToManyField(related_name='default_subscriptions', to='feed.rssfeed')),
            ],
        ),
    ]
