# Generated by Django 5.0.6 on 2024-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_rssfeed_pub_date_defaultsubscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds', models.ManyToManyField(related_name='default_subscription', to='feed.rssfeed')),
            ],
        ),
        migrations.DeleteModel(
            name='DefaultSubscriptions',
        ),
    ]
