# Generated by Django 5.0.6 on 2024-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_defaultsubscription_delete_defaultsubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='default_page',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DefaultSubscription',
        ),
    ]
