# Generated by Django 5.0.6 on 2024-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_rssfeeditem_userbookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rssfeeditem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
