# Generated by Django 5.0.6 on 2024-07-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rssfeedcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.rssfeedcategory'),
        ),
    ]
