# Generated by Django 5.0.6 on 2025-02-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rssfeed_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
