# Generated by Django 5.0.6 on 2025-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_rssfeed_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSDateTimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
