# Generated by Django 5.0.6 on 2025-02-24 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_add_snapshot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeeditem',
            name='snapshot_id',
        ),
        migrations.AddField(
            model_name='rssfeeditem',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.rssdatetimeupdate'),
        ),
        migrations.AlterField(
            model_name='rssdatetimeupdate',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='collected_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
