# Generated by Django 5.0.6 on 2024-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rssfeed_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedItemSummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('requested_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeedItemSummaryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryRequestContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField()),
                ('api_provider', models.CharField(choices=[('chatgpt', 'OpenAI ChatGPT'), ('gemini', 'Google Gemini')], default='chatgpt', max_length=10)),
                ('engine', models.CharField(blank=True, max_length=10, null=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
