# Generated by Django 5.0.6 on 2024-07-25 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rssfeeditemsummaryrequest_rssfeeditemsummaryresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeeditemsummaryrequest',
            name='queued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rssfeeditemsummaryrequest',
            name='rss_feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_requests', to='feed.rssfeeditem'),
        ),
        migrations.AddField(
            model_name='rssfeeditemsummaryresponse',
            name='rss_feed_item_summary_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.rssfeeditemsummaryrequest'),
        ),
        migrations.AddField(
            model_name='rssfeeditemsummaryrequest',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.rssfeeditemsummaryresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='summaryrequestcontext',
            unique_together={('prompt_template', 'api_provider', 'engine', 'max_tokens')},
        ),
        migrations.AddField(
            model_name='rssfeeditemsummaryrequest',
            name='request_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_requests', to='feed.summaryrequestcontext'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='summary_request_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.summaryrequestcontext'),
        ),
    ]
