# Generated by Django 5.0.6 on 2024-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_summaryrequestcontext_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeeditemsummaryrequest',
            name='queued_by',
        ),
        migrations.AlterField(
            model_name='summaryrequestcontext',
            name='name',
            field=models.CharField(default='utzpmh', help_text='Not used with API provider call, a unique name identifier used to differentiate against multiple context choices.', max_length=255, unique=True),
        ),
    ]
